### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin-fileserver#1]
This repository should have a few simple integration tests to ensure the right files are served on the right routes with the right content types.

**Comment by ejmg** [comment]
I'll be taking a swing at this issue if nobody else is currently prioritizing it.

**Comment by ejmg** [comment]
Looking at this more, would an ultra-simplified version of spin's own integration tests be a good model to copy?

AFAICT, this library is meant to be used as a one off component, so testing behavior really just means building and running the component with spin and making test requests against it to check for the things mentioned above.
