### ISSUE TITLE
Default favicon

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin-fileserver#33]
The issue of web browsers requesting `/favicon.ico` is starting to become confusing.

I would like to suggest that we supply a default favicon icon, compiled into the file server — for example, the Spin logo.

Users could always override that by providing their own file at the root of the files.

Thoughts?

**Comment by lann** [comment]
Is the confusion due to logging? Maybe we should just suppress 404 logs for that path?

**Comment by ThorstenHans** [comment]
@radu-matei what about embedding the spin icon using [include_bytes!](https://doc.rust-lang.org/std/macro.include_bytes.html) and sending that one when the `facicon.ico` does not exist? 

This would eliminate the 404 in the first place and smoothen the onboarding process.

**Comment by radu-matei** [comment]
Yeah, the Spin logo with something like `include_bytes` could work!

**Comment by ThorstenHans** [comment]
Where can I get the favicon from 😄

**Comment by radu-matei** [comment]
![image](https://github.com/fermyon/spin-fileserver/assets/13103165/de568af3-7f7c-4ec8-8e7d-8d87677949da)

**Comment by ThorstenHans** [comment]
Awesome, so I'll take this one
