### ISSUE TITLE
Plans and time frame for release `0.0.4`?

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin-fileserver#42]
Hey @jpflueger,

do you have plans on cutting a new release (`0.0.4`)? Since `0.0.3`, several smaller features/improvements found its way into `main`.

Are there other features that you want to be implemented in order to release a new version?

**Comment by vdice** [comment]
I don't see a reason not to cut a release with the new features you've added @ThorstenHans.  We can always follow up with another if @jpflueger or others have some future requests.  I'd vote we bump to v0.1.0 and start incrementing this minor version as we cut non-patch releases.  I can usher this out next Monday.

**Comment by jpflueger** [comment]
I don’t have anything in the works so I think it makes sense to cut a new release. Might want to coordinate with the next spin release to update the templates there too.

**Comment by vdice** [comment]
[v0.1.0](https://github.com/fermyon/spin-fileserver/releases/tag/v0.1.0) is out.  Thanks @ThorstenHans for all of the improvements!
PR in Spin to bump to the latest: https://github.com/fermyon/spin/pull/1897
