### ISSUE TITLE
Exact routes serving single files

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin-fileserver#52]
Sometimes you want to serve a specific file but don't want to take over an entire wildcard hierarchy.  An example is `/favicon.ico` where you really, really cannot take over the `/...` wildcard.  At the moment the fileserver appears to only allow mounting directories/wildcards.  It would be good to allow individual files too.

**Comment by benwis** [comment]
This is a fairly significant pain point for me with Leptos apps on Spin, hoping it gets resolved soon
